import {Good} from '../components/confing/interfaces'


const GOODS:Good[]= [
  {
    "img": "./armchair/strandmon/2.jpg",
    "title": "STRANDMON",
    "categories": "armchair",
    "values": 5,
    "year": 2010,
    "cart": 0,
    "color": "gray",
    "brand": "IKEA",
    "price": 299.99,
    "description": "New life for an old friend. We first discovered this chair to customers in the 1950s. After 60 years, it is again included in our assortment and does not at all pass to conscious actions in comfort and desires.",
  },
  {
    "img": "./bed/elanda/1.jpg",
    "title": "Elanda 1",
    "categories": "bed",
    "values": 10,
    "year": 2012,
    "cart": 0,
    "color": "black",
    "brand": "Halmar",
    "price": 499.99,
    "description": "The luxurious double bed Halmar Elanda will decorate your bedroom in a modern style, where you can relax wonderfully after a hard day.",
    "size": "160x200"
  },
  {
    "img": "./bed/elanda/2.jpg",
    "title": "Elanda 2",
    "categories": "bed",
    "values": 10,
    "year": 2012,
    "cart": 0,
    "color": "blue",
    "brand": "Halmar",
    "price": 499.99,
    "description": "The luxurious double bed Halmar Elanda will decorate your bedroom in a modern style, where you can relax wonderfully after a hard day.",
    "size": "160x200"
  },
  {
    "img": "./bed/elanda/3.jpg",
    "title": "Elanda 3",
    "categories": "bed",
    "values": 10,
    "year": 2012,
    "cart": 0,
    "color": "gray",
    "brand": "Halmar",
    "price": 599.99,
    "description": "The luxurious double bed Halmar Elanda will decorate your bedroom in a modern style, where you can relax wonderfully after a hard day.",
    "size": "160x200"
  },
  {
    "img": "./desk/nelson/2.jpg",
    "title": "Nelson",
    "categories": "desk",
    "values": 3,
    "year": 2015,
    "cart": 0,
    "color": "brown",
    "brand": "INSPIRE Q",
    "price": 359.99,
    "description": "Store all of your papers, books and other materials with the Nelson Rustic Industrial Desk from iNSPIRE Q® Classic. A perfect addition to any home office, living room or bedroom, this versatile piece includes four shelves as well as ample table space, giving you plenty of room to work. The industrial styling of this desk includes a combination of poplar wood and metal for a truly rustic vibe.",
  },
  
  {
    "img": "./bookshelf/edison/2.jpg",
    "title": "Industrial 5",
    "categories": "bookshelf",
    "values": 4,
    "year": 2015,
    "cart": 0,
    "color": "brown",
    "brand": "Walker Edison",
    "price": 249.99,
    "description": "This 5-shelf urban pipe bookcase is perfect for a trendy, industrial-chic look. With a durable metal frame, and a sleek woodgrain finish made from high-grade manufactured wood, this piece is reliable to hold all of your books, trinkets, and collectables, while complementing any home office, hallway, living room, or bedroom.",
    "shelf": 5
  },
  {
    "img": "./kitchen/bodarp/2.jpg",
    "title": "Bodarp",
    "categories": "kitchen",
    "values": 6,
    "year": 2017,
    "cart": 0,
    "color": "olive",
    "brand": "IKEA",
    "price": 799.99,
    "description": "Produced in factories using renewable electricity and featuring a foil made of recycled PET bottles, BODARP doors in matt grey-green create an open and welcoming kitchen with a modern twist. The BODARP series in grey-green will give your kitchen a modern feel with its clean lines and matt surface.",
  },
  {
    "img": "./sofa/frame/2.jpg",
    "title": "Frame 1",
    "categories": "sofa",
    "values": 3,
    "year": 2021,
    "cart": 0,
    "color": "gray",
    "brand": "Halmar",
    "price": 1299.99,
    "description": "The innovative idea of ​​this sofa is to present it as a platform, the back or side of which can be used as a free surface or an informal seat.",
  },
  {
    "img": "./sofa/frame/3.jpg",
    "title": "Frame 2",
    "categories": "sofa",
    "values": 3,
    "year": 2021,
    "cart": 0,
    "color": "black",
    "brand": "Halmar",
    "price": 1199.99,
    "description": "The innovative idea of ​​this sofa is to present it as a platform, the back or side of which can be used as a free surface or an informal seat.",
  },
  {
    "img": "./lamp/artap/3.jpg",
    "title": "Artap 1",
    "categories": "lamp",
    "values": 12,
    "year": 2018,
    "cart": 0,
    "color": "black",
    "brand": "Walker Edison",
    "price": 119.99,
    "description": "Modern style LED lamp, made of high quality iron and wood, warm white light. LED table lamps are suitable for living room, bedroom, children's room, office, store, hotel, restaurant, library and study.",
    
  },
  {
    "img": "./lamp/artap/4.jpg",
    "title": "Artap 2",
    "categories": "lamp",
    "values": 12,
    "year": 2018,
    "cart": 0,
    "color": "white",
    "brand": "Walker Edison",
    "price": 119.99,
    "description": "Modern style LED lamp, made of high quality iron and wood, warm white light. LED table lamps are suitable for living room, bedroom, children's room, office, store, hotel, restaurant, library and study.",
    
  },
  {
    "img": "./armchair/inspire/2.jpg",
    "title": "Inspire",
    "categories": "armchair",
    "values": 6,
    "year": 2013,
    "cart": 0,
    "color": "gray",
    "brand": "INSPIRE Q",
    "price": 499.99,
    "description": "This modern chair is perfect for those who like to relax and unwind.",
  }
]

export default GOODS